name:                tuiped-ssh
version:             0.1.0.0
github:              "bronen/tuiped-ssh"
license:             BSD-3-Clause
author:              "Brenno Rodrigues"
maintainer:          "contact@bronen.com.br"
copyright:           "2025 Brenno Rodrigues"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bronen/tuiped-ssh#readme>

dependencies:
- base >= 4.7 && < 5
- data-default == 0.8.0.1
- hssh == 0.1.0.0
- socket == 0.8.3.0
- vty == 6.4
- vty-unix == 0.2.0.0
- memory == 0.18.0
- bytestring == 0.12.1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  tuiped-ssh-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tuiped-ssh

tests:
  tuiped-ssh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tuiped-ssh
